// <auto-generated />
using System;
using BookStore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.API.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BookStore.API.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Andrzej Sapkowski",
                            CreatedDate = new DateTime(2025, 5, 23, 11, 4, 35, 757, DateTimeKind.Local).AddTicks(7624),
                            Description = "Pierwszy tom kultowej sagi o wiedźminie",
                            ISBN = "9788375780635",
                            Price = 39.99m,
                            Stock = 10,
                            Title = "Wiedźmin: Ostatnie życzenie"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.R.R. Tolkien",
                            CreatedDate = new DateTime(2025, 5, 23, 11, 4, 35, 757, DateTimeKind.Local).AddTicks(7631),
                            Description = "Klasyczna powieść fantasy",
                            ISBN = "9788324159819",
                            Price = 49.99m,
                            Stock = 5,
                            Title = "Hobbit, czyli tam i z powrotem"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            CreatedDate = new DateTime(2025, 5, 23, 11, 4, 35, 757, DateTimeKind.Local).AddTicks(7637),
                            Description = "Rok 1984 w wersji orwellowskiej",
                            ISBN = "9788382022287",
                            Price = 29.99m,
                            Stock = 8,
                            Title = "1984"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
